# Generated by Django 5.2 on 2025-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='Status',
            field=models.CharField(db_column='Status', default='Active', max_length=50),
        ),
    ]
