import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Container, Card, Form, Button, Alert, Spinner } from 'react-bootstrap';
import api from '../services/api';

function JobApplicationForm() {
  const { id } = useParams(); // Job ID
  const navigate = useNavigate();

  const [job, setJob] = useState(null);
  const [jobTitle, setJobTitle] = useState('');
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [phone, setPhone] = useState('');
  const [resume, setResume] = useState(null);
  const [coverLetter, setCoverLetter] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [verificationStatus, setVerificationStatus] = useState('');
  const [verificationFeedback, setVerificationFeedback] = useState('');

  const ucid = localStorage.getItem('ucid');
  const userRole = localStorage.getItem('userRole');
  const moderatorId = localStorage.getItem('moderatorId');
  
  // Check if user is authorized
  useEffect(() => {
    if (!ucid || userRole !== 'student') {
      navigate('/login');
    }
  }, [ucid, userRole, navigate]);
  
  // Check verification status
  useEffect(() => {
    const checkVerification = async () => {
      try {
        // Check if user is a moderator (moderators are automatically verified)
        if (moderatorId) {
          setVerificationStatus('Verified');
          return;
        }
        
        // For non-moderators, check verification status
        const response = await api.checkVerificationStatus('student', ucid);
        setVerificationStatus(response.data.status);
        setVerificationFeedback(response.data.feedback);
      } catch (err) {
        console.error("Error checking verification status:", err);
      }
    };
    
    if (ucid) {
      checkVerification();
    }
  }, [ucid, moderatorId]);

  // Fetch job details and user data
  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        
        // Fetch job details
        const jobRes = await api.getJob(id);
        
        // Handle backend vs frontend format
        if (jobRes.data) {
          const jobData = jobRes.data;
          
          // Format data based on backend vs frontend field names
          setJob(jobData);
          setJobTitle(jobData.jobTitle || jobData.JobTitle || '');
          
          // Try to get employer details to attach to application
          let employerId = jobData.employerId || jobData.Employer;
          
          // Get student profile data
          try {
            const studentRes = await api.getStudentProfile(ucid);
            if (studentRes.data) {
              setFirstName(studentRes.data.FName || studentRes.data.firstName || '');
              setLastName(studentRes.data.LName || studentRes.data.lastName || '');
            }
          } catch (err) {
            console.error('Error fetching student data:', err);
          }
        }
        
        setLoading(false);
      } catch (err) {
        console.error('Error loading application form:', err);
        setError('Failed to load job data. Please try again.');
        setLoading(false);
      }
    };
    
    if (id) {
      fetchData();
    }
  }, [id, ucid]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Prevent unverified students from submitting (except moderators who are automatically verified)
    if (verificationStatus !== 'Verified' && !moderatorId) {
      setError('Your account must be verified before you can apply for jobs.');
      return;
    }
    
    try {
      setLoading(true);
      
      // Format application data to exactly match the backend schema
      const formattedData = {
        // ApplicationID is auto-generated by the backend
        Status: 'Submitted',
        DateApplied: new Date().toISOString().split('T')[0],
        ApplicantUCID: parseInt(ucid),
        JobID: parseInt(id),
        EmployerID: parseInt(job.employerId || job.Employer)
      };
      
      console.log('Submitting job application with data:', formattedData);
      
      // Submit application to the API endpoint
      const response = await api.post('/job-applications/', formattedData);

      setMessage('Application submitted successfully!');
      setError('');
      setTimeout(() => navigate('/application-history'), 1500);
      setLoading(false);
    } catch (err) {
      console.error('Submission failed:', err);
      setError('Application failed: ' + (err.response?.data?.message || 'Please try again.'));
      setMessage('');
      setLoading(false);
    }
  };

  // Check if student is verified - also consider moderators as verified
  const isVerified = verificationStatus === 'Verified' || !!moderatorId;
  const isPending = verificationStatus === 'Pending' && !moderatorId;
  const isRejected = verificationStatus === 'Rejected' && !moderatorId;

  if (loading) {
    return (
      <Container className="py-5 text-center">
        <Spinner animation="border" variant="primary" />
      </Container>
    );
  }
  
  // If student is not verified, show appropriate message
  if (!isVerified) {
    return (
      <Container className="py-5">
        <Card className="p-4 shadow-sm">
          <Card.Body>
            <h3 className="mb-4 text-center">Account Verification Required</h3>
            
            {isPending && (
              <Alert variant="warning">
                <Alert.Heading>Verification Pending</Alert.Heading>
                <p>Your account is currently awaiting verification by a moderator. Once verified, you'll be able to apply for jobs.</p>
                <p>Please check back later or contact support if your account has been pending for more than 2 business days.</p>
              </Alert>
            )}
            
            {isRejected && (
              <Alert variant="danger">
                <Alert.Heading>Verification Rejected</Alert.Heading>
                <p>Your account verification was rejected. Please update your profile according to the feedback below:</p>
                <p className="mb-3"><strong>Feedback:</strong> {verificationFeedback}</p>
                <Button as={Link} to="/profile" variant="outline-danger">Update Profile</Button>
              </Alert>
            )}
            
            <div className="d-flex justify-content-between mt-4">
              <Button variant="secondary" onClick={() => navigate(-1)}>Go Back</Button>
              <Button variant="primary" as={Link} to="/browse">Browse Jobs</Button>
            </div>
          </Card.Body>
        </Card>
      </Container>
    );
  }

  return (
    <Container className="py-5">
      <Card className="p-4 shadow-sm">
        <Card.Body>
          <h3 className="mb-4 text-center">Apply to: {jobTitle}</h3>

          {message && <Alert variant="success">{message}</Alert>}
          {error && <Alert variant="danger">{error}</Alert>}

          <Form onSubmit={handleSubmit}>
            {/* Job Title (readonly) */}
            <Form.Group className="mb-3">
              <Form.Label>Job Title</Form.Label>
              <Form.Control type="text" value={jobTitle} disabled />
            </Form.Group>

            {/* Applicant First Name (readonly) */}
            <Form.Group className="mb-3">
              <Form.Label>First Name</Form.Label>
              <Form.Control type="text" value={firstName} disabled />
            </Form.Group>

            {/* Applicant Last Name (readonly) */}
            <Form.Group className="mb-3">
              <Form.Label>Last Name</Form.Label>
              <Form.Control type="text" value={lastName} disabled />
            </Form.Group>

            {/* Phone Number */}
            <Form.Group className="mb-3">
              <Form.Label>Phone Number</Form.Label>
              <Form.Control
                type="tel"
                placeholder="e.g., 403-123-4567"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                required
              />
            </Form.Group>

            {/* Resume Upload */}
            <Form.Group className="mb-3">
              <Form.Label>Upload Resume (PDF only)</Form.Label>
              <Form.Control
                type="file"
                accept="application/pdf"
                onChange={(e) => setResume(e.target.files[0])}
              />
              <Form.Text className="text-muted">
                Note: Your previously uploaded resume will be used if you don't upload a new one.
              </Form.Text>
            </Form.Group>

            {/* Optional Cover Letter */}
            <Form.Group className="mb-3">
              <Form.Label>Cover Letter</Form.Label>
              <Form.Control
                as="textarea"
                rows={5}
                placeholder="Introduce yourself and explain why you're a good fit for this position..."
                value={coverLetter}
                onChange={(e) => setCoverLetter(e.target.value)}
              />
            </Form.Group>

            <div className="d-flex justify-content-between">
              <Button variant="secondary" as={Link} to={`/jobs/${id}`}>
                Cancel
              </Button>
              <Button variant="primary" type="submit" disabled={loading}>
                {loading ? 'Submitting...' : 'Submit Application'}
              </Button>
            </div>
          </Form>
        </Card.Body>
      </Card>
    </Container>
  );
}

export default JobApplicationForm;
