# Generated by Django 5.2 on 2025-04-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('UCID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Major', models.CharField(blank=True, max_length=255, null=True)),
                ('GraduationYear', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('EmployerID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Industry', models.CharField(blank=True, max_length=255, null=True)),
                ('VerificationStatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('ModeratorID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'moderator',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('SUCID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='relay_data.student')),
                ('CGPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Resume', models.TextField()),
                ('VerificationStatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('SUCID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='relay_data.student')),
                ('Hours', models.IntegerField()),
            ],
            options={
                'db_table': 'volunteer',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Location', models.CharField(max_length=255)),
                ('Deadline', models.DateField()),
                ('Employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.employer')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50)),
                ('DateApplied', models.DateField()),
                ('ApplicantUCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.student')),
                ('Employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.employer')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.job')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='EmployerVerification',
            fields=[
                ('VID', models.AutoField(primary_key=True, serialize=False)),
                ('VerificationStatus', models.CharField(max_length=50)),
                ('VerificationDate', models.DateField()),
                ('Employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.employer')),
                ('Moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.moderator')),
            ],
            options={
                'db_table': 'employerverification',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('Date', models.DateField()),
                ('VUCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.student')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('VID', models.AutoField(primary_key=True, serialize=False)),
                ('VerificationStatus', models.CharField(max_length=50)),
                ('VerificationDate', models.DateField()),
                ('ApplicantUCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.student')),
                ('Moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.moderator')),
            ],
            options={
                'db_table': 'verification',
            },
        ),
        migrations.CreateModel(
            name='JobModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.employer')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.job')),
                ('Moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay_data.moderator')),
            ],
            options={
                'db_table': 'jobmoderation',
                'unique_together': {('Moderator', 'Job', 'Employer')},
            },
        ),
    ]
